### ISSUE TITLE
[1.20.4] LootMixin class cast/inventory issues

### ISSUE THREAD

**Issue by noobanidus** [alfiae/item-modifiers#1]
Someone reported this mod as not being compatible with Lootr, although when I looked at the crash report that was provided, it appeared to be a core issue with [LootMixin.java](https://github.com/alfiae/item-modifiers/blob/1.20.x/src/main/java/com/alfred/modifiers/mixin/LootMixin.java#L26).

You appear to be casting `this` (an instance of `LootTable`) into `LootableInventory` on line 26, which is always going to fail; I'm assuming you were trying to access the actual `inventory` that's passed in to that function. Likewise, you shouldn't even need to cast it, as the `getStack` method is part of `Inventory` rather than `LootableInventory`.

Here's the full report, unfortunately I've forgotten the URL to de-obfuscate crash reports:

```
java.lang.ClassCastException: class net.minecraft.class_52 cannot be cast to class net.minecraft.class_8934 (net.minecraft.class_52 and net.minecraft.class_8934 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @d8355a8)
        at net.minecraft.class_52.handler$cil000$itemmodifiers$applyLootModifiers(class_52.java:2026) ~[server-intermediary.jar:?]
        at net.minecraft.class_52.method_329(class_52.java:153) ~[server-intermediary.jar:?]
        at net.zestyblaze.lootr.blocks.entities.LootrBarrelBlockEntity.unpackLootTable(LootrBarrelBlockEntity.java:139) ~[lootr-1.20.4-0.8.31.78.jar:?]
        at net.zestyblaze.lootr.data.ChestData.createInventory(ChestData.java:218) ~[lootr-1.20.4-0.8.31.78.jar:?]
        at net.zestyblaze.lootr.data.DataStorage.getInventory(DataStorage.java:197) ~[lootr-1.20.4-0.8.31.78.jar:?]
        at net.zestyblaze.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:115) ~[lootr-1.20.4-0.8.31.78.jar:?]
        at net.zestyblaze.lootr.blocks.LootrBarrelBlock.method_9534(LootrBarrelBlock.java:54) ~[lootr-1.20.4-0.8.31.78.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1223) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:348) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1134) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by alfuwu** [comment]
Odd, I don't know what I was thinking. It didn't crash in my dev environment when I tested it, which it definitely should have. It should be fixed now.
